---
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Test suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
        lxml-range:
          - "lxml>=4.0.0,<5.0"
          - "lxml>=5.0.0"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} for ${{ matrix.lxml-range }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade wheel
          python -m pip install --upgrade -r requirements.txt
          python -m pip install --upgrade "${{ matrix.lxml-range }}"
          python -m pip install -e .
      - name: Lint
        run: |
          isort -c xmlunittest.py
          flake8 xmlunittest.py
      - name: Test
        run: pytest test.py
